### ISSUE TITLE
ptools is not loaded on platform x64-mingw32

### ISSUE THREAD

**Issue by ssaunier** [djberg96/ptools#24]
Hello,

I have the weirdest error on my Windows7 in Virtual Box:

I can require `ptools` from irb:

``` bash
$ irb
irb> require "ptools"
=> true
```

But when I try to require it in a bundler context:

``` bash
$ bundle exec irb
irb> require "ptools"
LoadError: cannot load such file -- ptools
        from (irb):7:in `require'
        from (irb):7
        from C:/Ruby21-x64/bin/irb:11:in `<main>'
```

In my Gemfile, I have:

``` ruby
# Windows dependencies of middleman-deploy gem
gem 'ptools', platforms: [:mswin, :mingw, :x64_mingw]
gem 'win32-file', platforms: [:mswin, :mingw, :x64_mingw]
```

The gem is on my computer:

``` bash
$ bundle show ptools
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/ptools-1.3.2-universal-mingw32
```

But somehow, when I run `bundle exec irb`, the `$LOAD_PATH` does not contain the folder above.

Do you have any idea what could cause this problem? I suspect it's not specific to the gem code, but I am not very familiar with the gem loading mechanism, I posted this issue. Thank you very much for your help!

**Comment by ssaunier** [comment]
Possibly related to https://github.com/karlfreeman/middleman-deploy/issues/62

**Comment by djberg96** [comment]
I don't remember bundler's platform handling. What if you add "mingw32"?

**Comment by ssaunier** [comment]
﻿﻿﻿﻿Hi @djberge96, thanks for your quick anser :).
The platform `mingw32` does not appear to exist. I tried removing the
platform option from the gem lines, but the problem sticks.

I guess I'll have to dive into the rubygems code to debug what's happenning.
I'll post here what I find, if I find something :)

**Comment by djberg96** [comment]
I wonder if the "universal" is confusing it.

**Comment by djberg96** [comment]
@ssaunier Is this still happening?
