### ISSUE TITLE
`File.binary?` mistakes binary pfx files as text

### ISSUE THREAD

**Issue by ElvenSpellmaker** [djberg96/ptools#28]
As is shown in the image below of a snippet of a `pfx` file, this file is clearly binary but the `File.binary?` method says it's `false`/text.

![image](https://user-images.githubusercontent.com/2286713/27730309-a999a5dc-5d80-11e7-8a42-fbeb69df6397.png)

**Comment by ElvenSpellmaker** [comment]
I see the line `((s.size - s.grep(" ".."~").size) / s.size.to_f) > 0.30` and now understand it to mean that 30% of the bytes are "binary".

30% seems a little high for this check, at the very least maybe add the percentage as a second optional parameter to `File.binary?` so that the percentage may be customised if desired?

**Comment by djberg96** [comment]
@ElvenSpellmaker Sure, I can do that.

**Comment by djberg96** [comment]
@ElvenSpellmaker Best I can do for now: https://github.com/djberg96/ptools/pull/29

**Comment by ElvenSpellmaker** [comment]
Excellent, thanks! =)
