### ISSUE TITLE
Default behavior of ::Pathname.parent() on Windows is changed

### ISSUE THREAD

**Issue by jakkn** [djberg96/ptools#31]
Simply adding `require 'ptools'` in a script that uses Pathname.parent() throws an error. If the working directory is one step further down then everything is fine.

OS: Win 10 x64
```
jakob /c/Users $ ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
jakob /c/Users $ cat test.rb
```
```Ruby
require 'pathname'
require 'ptools'
require 'win32-file'

puts Pathname.pwd
puts Pathname.pwd.parent
```
```
jakob /c/Users $ ruby test.rb
C:/tools/ruby24/lib/ruby/2.4.0/pathname.rb:44:in `[]': no implicit conversion from nil to integer (TypeError)
        from C:/tools/ruby24/lib/ruby/2.4.0/pathname.rb:44:in `chop_basename'
        from C:/tools/ruby24/lib/ruby/2.4.0/pathname.rb:370:in `plus'
        from C:/tools/ruby24/lib/ruby/2.4.0/pathname.rb:350:in `+'
        from C:/tools/ruby24/lib/ruby/2.4.0/pathname.rb:186:in `parent'
        from test.rb:6:in `<main>'
C:/Users
jakob /c/Users $ cd jakob/
jakob ~ $ ruby ../test.rb
C:/Users/jakob
C:/Users
jakob ~ $
```

**Comment by djberg96** [comment]
Hm, we must've redefined a method that Ruby has since defined, and that's making pathname barf. I would start by commenting everything in ptools.rb out, and uncommenting it one method at a time until we find the culprit.

**Comment by jakkn** [comment]
I gave it a quick shot but commenting out everything in ptools.rb caused no changes, so the gem must be read from another file. I have little experience debugging gems, and not much time this week so I'm afraid I won't be able to come up with a fix anytime soon.

**Comment by djberg96** [comment]
I wonder if it's win32-file then.

**Comment by jakkn** [comment]
That did it.

**Comment by djberg96** [comment]
Ok, so win32-file redefined some core methods, and this must be causing Pathname to bomb. I turned over almost all of the win32 libraries over to the chef folks, so I would suggest posting your issue over there.

I'll go ahead and close this one for now. Please reopen it if it does turn out to come back to this library.

**Comment by djberg96** [comment]
Also note that you could use pathname2 instead of pathname, if that's an option.

**Comment by jakkn** [comment]
Will do, thanks!
