### ISSUE TITLE
ptools@1.4.2 | LoadError:   cannot load such file -- win32/file on Windows

### ISSUE THREAD

**Issue by CAMOBAP** [djberg96/ptools#42]
First of all thanks for your gem!

### Problem

Code https://github.com/djberg96/ptools/blob/main/ptools.gemspec#L33-L35 doesn't work for gems from rubygems.org, unfortunately, there is no platform-specific dependencies on install time and `gemspec` evaluated at build time more details here https://stackoverflow.com/questions/4596606/rubygems-how-do-i-add-platform-specific-dependency

### Possible solution

Looks like [for 1.4.1 you did a special release for win32](https://rubygems.org/gems/ptools/versions/1.4.1-universal-mingw32), could you please do the same release for 1.4.2?

Thanks

**Comment by djberg96** [comment]
Oops, guess I forgot. I just pushed out 1.4.2 for Windows.
