### ISSUE TITLE
More image extensions

### ISSUE THREAD

**Issue by mcandre** [djberg96/ptools#8]
- pdf
- tiff
- ico

**Comment by djberg96** [comment]
Does this work for .ico?

    def self.ico?(file)
      ["\000\000\001\000", "\000\000\002\000"].include?(IO.read(file, 4, nil, :encoding => 'binary'))
    end

**Comment by djberg96** [comment]
I've added a check for .ico in 1.3.5. I'm not going to treat PDF's as an image because I don't see a consensus that PDF's should be treated as such. Anyway, thanks for the suggestions!
